### ISSUE TITLE
Error message for duplicate record keys does not specify which keys are duplicated

### ISSUE THREAD

**Issue by MaybeJustJames** [MaybeJustJames/yaml#26]
Thanks @ypyl

Reference: https://github.com/MaybeJustJames/yaml/pull/25#issuecomment-1196392092

**Comment by MaybeJustJames** [comment]
@ypyl how do you feel about the change in the linked PR? It lists the duplicated keys. It's not much information but maybe helpful?

**Comment by ypyl** [comment]
Looks great to me! thank you very much for this PR!

**Comment by MaybeJustJames** [comment]
Great :) I'll roll a release then
